# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f242441362039919c26ea15c69c507bcb2feb5756d487bebed342f78f7c47889959817b6cbbb739967be3071d148d8d47d2f053cfb3ba03515bfc70112223347

test:
  secret_key_base: 00df3dfbbf1c871f7e5b1d659d12f0a4c28f1ba0c00c54742ffb38d0df4eaf1eead6141aaed05489ea221fd5870e6e5da2b461b846bbd6d0a0878be74866ce09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
